//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/InputSystem/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""fb391da8-7258-4ddb-9d57-4f97937cdac8"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""3b910c82-6264-4d11-b4b1-9b8e738dcc88"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""Value"",
                    ""id"": ""718936ba-3968-4424-a943-ba819de3f704"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6c0dd135-1c23-411f-9206-e25abfcf62b9"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""28a346da-1fbd-40b2-bf66-864daf714f50"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4cb9ecdb-dcc5-4a9f-b3db-2f4c265e7812"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0dd38373-7e43-4a1c-bddc-7f53322727df"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1575b8bf-b706-4cf5-9f6e-cbf3e664896b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""96e2c8a8-c0d6-49d2-94c9-3742c9f159f6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""be5c309c-30cf-4175-bb57-c260fce15979"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""768cc4ae-4cd6-453b-bbf6-655fed6bbd47"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Stage1"",
            ""id"": ""e29ea919-df65-43e6-85bf-c6becfde67bf"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""836a399c-91c5-403c-979d-7b17e07d62e1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""10b977ff-17b6-436b-82a8-6a66a55368b6"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7010f2cc-9234-4a2f-9626-b29d80b70430"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2ba105d4-432f-4a92-8b6c-c011ae20194a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""637759ec-01fb-4808-94bf-673706e2116e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""964a67e7-8a56-40ef-ab79-63d064415cf1"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""134002c3-bdb2-4742-9797-1c4bd34220fd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Stage2"",
            ""id"": ""5cf81c34-c6bd-4cbd-9cb8-c30ce02615d6"",
            ""actions"": [
                {
                    ""name"": ""SelectUp"",
                    ""type"": ""Button"",
                    ""id"": ""c25b6bd4-4d0e-4a75-9497-9b4674874db2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectDown"",
                    ""type"": ""Button"",
                    ""id"": ""4eebcca8-bd83-4cc3-a670-d83589d54d0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""ade9c65b-07f7-4290-92e5-ad65f473e147"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointerMove"",
                    ""type"": ""Value"",
                    ""id"": ""97964740-0d87-4fd8-a9c5-5ead4fb19282"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ee783c0a-679c-4b55-800f-71703278bb1f"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08a910c6-49b0-4cdf-a434-81bfa5ea560f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""649a6933-57b5-4b1e-9423-50736f641852"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab228518-f8d0-4d2b-96ad-39320cf75e8c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7550997b-f2b1-40a8-87fb-1b499b154f31"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea197805-209a-440f-b49e-34e6bd936136"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3412da19-c0e3-4d4d-aada-7d55d4bbb967"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""25bce9ac-d04d-49c5-aa23-1d9dda11e1bc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0a93786f-23dd-49e6-821c-f7a0dba37ee9"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ca8d9b2b-6c02-420d-9799-f1c4af7f93e7"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2efb85fb-5a0d-4ae4-8e6a-73c7cf18c3ae"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""102fe259-a6a1-40d6-8243-144b8c171455"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PointerMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Stage3"",
            ""id"": ""14910024-ca5c-4732-84f4-38130f8ef1ba"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""463fd3e6-4898-4749-8574-6e4068a43731"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""bdc5057c-fb7f-4fd9-bbae-b727f5a45f8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnLeft"",
                    ""type"": ""Button"",
                    ""id"": ""8d95b1ab-cb21-4291-af2c-21b68933d666"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnRight"",
                    ""type"": ""Button"",
                    ""id"": ""e26ba21a-13ae-468d-8df0-43b93297f8b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""68880c16-50f1-45f8-8d61-084dd5038f02"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e8b42287-fb11-4d49-939a-de60b0309a5c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5d6552c4-e5fd-40fe-a07e-bd7f380d8c23"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""71ab5a4d-33bc-48af-b642-b098fee57812"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0e49a530-b026-4f18-857e-ab4f11b6cdc4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4cb2a25d-1cbe-445a-a8d4-b843d7d66f16"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed230e35-5a4d-47c1-9217-67382d74262c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5610213-abab-4dbf-8cc9-cb44dba6c205"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2805029a-c1dd-4977-920c-6300c14ba335"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""028181bc-a09b-490d-87fa-3f4b8dfb70fa"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39193a92-1e6b-4fd7-86f5-ced82f39c67e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9638ebd-501c-460e-9a34-a3926733e938"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UIInput"",
            ""id"": ""3947145d-1e27-45f9-85f0-c16f202b6c28"",
            ""actions"": [
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""e6627b80-bdf7-4b14-b8ee-c880af5f1a70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""0187f5bb-0cd5-4894-abe7-aab13fdc04fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""6622802f-2fcf-41ef-bfe3-72e972d5aee4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a2ab286c-a2bf-4e9e-8c10-66f232eb3e26"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""A"",
                    ""type"": ""Button"",
                    ""id"": ""129031ab-540f-47e6-a725-29c39a17bcd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""B"",
                    ""type"": ""Button"",
                    ""id"": ""b31cd3ec-dce7-49c1-90e2-b52e4c39a35d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""X"",
                    ""type"": ""Button"",
                    ""id"": ""c7bbe2a6-e1fe-4d5f-8787-6cb42571199d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Y"",
                    ""type"": ""Button"",
                    ""id"": ""64de7b37-20bf-4773-a43e-cfe34e89108d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftCrossKey"",
                    ""type"": ""Button"",
                    ""id"": ""ade900f4-441e-4d41-8aa4-33c1146483f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightCrossKey"",
                    ""type"": ""Button"",
                    ""id"": ""eeb2ae62-ebf1-4ef0-88a0-984768340931"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cf9470d0-3a31-4a67-adae-5121235eb7ee"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a048f618-65d2-4a9a-a807-7803bfa6c256"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32ab7013-669d-4ad0-9760-151597f16d30"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ff7a7cc-7c8f-43c2-aa3e-9fd50952e2cf"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc737f02-8910-4878-bbb1-7f74c8e3bbcb"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f06a01c8-58c1-4642-b628-5eb7a97ded5f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dcbbe0a-cb50-4950-8d92-741636f20eb8"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""086139aa-a52c-46ad-992e-ccee81c31205"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a0c97d35-5b39-4495-aefc-afaf613a62ac"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a1fb263e-bc59-4f1d-a1b9-1fab597fe4ca"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""30134710-5ac5-465c-9847-eda7cd37ad29"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d7086bcb-63e5-45a0-ab0a-c0428dbda70d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""D-Pad"",
                    ""id"": ""31fc19c0-e5f8-4089-9283-38e2c000cb1d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6dba68f0-2bf7-4f9a-ae38-7337257ebe65"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fc6479db-9a06-49f2-9071-3ac1383713e6"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""03d8ebe5-5bee-4e28-a4fb-0afaf6bdd981"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8a5e8c9c-4b68-42ec-b667-03116fcdd11a"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c20d4077-10bd-4330-94cc-9522e15a90d2"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1c5303d-5405-41d1-9f1c-2211bf11b55c"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""A"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49c99eb8-3ba2-4d16-8d6e-cbea6636f16e"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftCrossKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eecdc2b9-8c4b-4473-9527-6d7338bee6f8"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightCrossKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1cde4d1-748c-4854-b4c7-c9755e113f46"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""B"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f320a6e-15a0-44a6-a788-214a03790bf7"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd4ac1eb-cd36-4fc7-89f2-96f553aed951"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d210a92-6258-4188-8ba5-f314cb87801b"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b022243f-6da1-4d68-a17a-5344b75969ee"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""X"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Stage_Boss"",
            ""id"": ""34b6e932-2c6d-4336-8b4e-676fe99b5e34"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a4240824-1a6e-40cd-a9f9-30c2bfb5717a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""Value"",
                    ""id"": ""8478e294-7e68-41e2-81b3-83bf6b561e63"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4bfcf47a-3309-44df-aa28-5fbc56f8a46b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""7d579b67-cb89-4bb8-8050-89dbf1162541"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""869b654f-8fba-42df-bca4-ca7b9f69e088"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""12fcca32-0d08-47f5-969f-ad15d4661dac"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0199ad88-5139-48bb-9aa4-f62f92812ae0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6328b646-10de-4eef-a2fb-7fa10b2baaa1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1cb843a7-f3f0-4293-8af4-98806a244ee0"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6ba72cd-0619-46ca-aa36-5ee8ddd0c3c2"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Camera = m_Player.FindAction("Camera", throwIfNotFound: true);
        // Stage1
        m_Stage1 = asset.FindActionMap("Stage1", throwIfNotFound: true);
        m_Stage1_Move = m_Stage1.FindAction("Move", throwIfNotFound: true);
        // Stage2
        m_Stage2 = asset.FindActionMap("Stage2", throwIfNotFound: true);
        m_Stage2_SelectUp = m_Stage2.FindAction("SelectUp", throwIfNotFound: true);
        m_Stage2_SelectDown = m_Stage2.FindAction("SelectDown", throwIfNotFound: true);
        m_Stage2_Enter = m_Stage2.FindAction("Enter", throwIfNotFound: true);
        m_Stage2_PointerMove = m_Stage2.FindAction("PointerMove", throwIfNotFound: true);
        // Stage3
        m_Stage3 = asset.FindActionMap("Stage3", throwIfNotFound: true);
        m_Stage3_Move = m_Stage3.FindAction("Move", throwIfNotFound: true);
        m_Stage3_Throw = m_Stage3.FindAction("Throw", throwIfNotFound: true);
        m_Stage3_TurnLeft = m_Stage3.FindAction("TurnLeft", throwIfNotFound: true);
        m_Stage3_TurnRight = m_Stage3.FindAction("TurnRight", throwIfNotFound: true);
        // UIInput
        m_UIInput = asset.FindActionMap("UIInput", throwIfNotFound: true);
        m_UIInput_Submit = m_UIInput.FindAction("Submit", throwIfNotFound: true);
        m_UIInput_Cancel = m_UIInput.FindAction("Cancel", throwIfNotFound: true);
        m_UIInput_Click = m_UIInput.FindAction("Click", throwIfNotFound: true);
        m_UIInput_Move = m_UIInput.FindAction("Move", throwIfNotFound: true);
        m_UIInput_A = m_UIInput.FindAction("A", throwIfNotFound: true);
        m_UIInput_B = m_UIInput.FindAction("B", throwIfNotFound: true);
        m_UIInput_X = m_UIInput.FindAction("X", throwIfNotFound: true);
        m_UIInput_Y = m_UIInput.FindAction("Y", throwIfNotFound: true);
        m_UIInput_LeftCrossKey = m_UIInput.FindAction("LeftCrossKey", throwIfNotFound: true);
        m_UIInput_RightCrossKey = m_UIInput.FindAction("RightCrossKey", throwIfNotFound: true);
        // Stage_Boss
        m_Stage_Boss = asset.FindActionMap("Stage_Boss", throwIfNotFound: true);
        m_Stage_Boss_Move = m_Stage_Boss.FindAction("Move", throwIfNotFound: true);
        m_Stage_Boss_Camera = m_Stage_Boss.FindAction("Camera", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Camera;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Camera => m_Wrapper.m_Player_Camera;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Camera.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCamera;
                @Camera.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCamera;
                @Camera.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCamera;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Camera.started += instance.OnCamera;
                @Camera.performed += instance.OnCamera;
                @Camera.canceled += instance.OnCamera;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Stage1
    private readonly InputActionMap m_Stage1;
    private IStage1Actions m_Stage1ActionsCallbackInterface;
    private readonly InputAction m_Stage1_Move;
    public struct Stage1Actions
    {
        private @PlayerControls m_Wrapper;
        public Stage1Actions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Stage1_Move;
        public InputActionMap Get() { return m_Wrapper.m_Stage1; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Stage1Actions set) { return set.Get(); }
        public void SetCallbacks(IStage1Actions instance)
        {
            if (m_Wrapper.m_Stage1ActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_Stage1ActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_Stage1ActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_Stage1ActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_Stage1ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public Stage1Actions @Stage1 => new Stage1Actions(this);

    // Stage2
    private readonly InputActionMap m_Stage2;
    private IStage2Actions m_Stage2ActionsCallbackInterface;
    private readonly InputAction m_Stage2_SelectUp;
    private readonly InputAction m_Stage2_SelectDown;
    private readonly InputAction m_Stage2_Enter;
    private readonly InputAction m_Stage2_PointerMove;
    public struct Stage2Actions
    {
        private @PlayerControls m_Wrapper;
        public Stage2Actions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectUp => m_Wrapper.m_Stage2_SelectUp;
        public InputAction @SelectDown => m_Wrapper.m_Stage2_SelectDown;
        public InputAction @Enter => m_Wrapper.m_Stage2_Enter;
        public InputAction @PointerMove => m_Wrapper.m_Stage2_PointerMove;
        public InputActionMap Get() { return m_Wrapper.m_Stage2; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Stage2Actions set) { return set.Get(); }
        public void SetCallbacks(IStage2Actions instance)
        {
            if (m_Wrapper.m_Stage2ActionsCallbackInterface != null)
            {
                @SelectUp.started -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnSelectUp;
                @SelectUp.performed -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnSelectUp;
                @SelectUp.canceled -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnSelectUp;
                @SelectDown.started -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnSelectDown;
                @SelectDown.performed -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnSelectDown;
                @SelectDown.canceled -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnSelectDown;
                @Enter.started -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnEnter;
                @Enter.performed -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnEnter;
                @Enter.canceled -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnEnter;
                @PointerMove.started -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnPointerMove;
                @PointerMove.performed -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnPointerMove;
                @PointerMove.canceled -= m_Wrapper.m_Stage2ActionsCallbackInterface.OnPointerMove;
            }
            m_Wrapper.m_Stage2ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SelectUp.started += instance.OnSelectUp;
                @SelectUp.performed += instance.OnSelectUp;
                @SelectUp.canceled += instance.OnSelectUp;
                @SelectDown.started += instance.OnSelectDown;
                @SelectDown.performed += instance.OnSelectDown;
                @SelectDown.canceled += instance.OnSelectDown;
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
                @PointerMove.started += instance.OnPointerMove;
                @PointerMove.performed += instance.OnPointerMove;
                @PointerMove.canceled += instance.OnPointerMove;
            }
        }
    }
    public Stage2Actions @Stage2 => new Stage2Actions(this);

    // Stage3
    private readonly InputActionMap m_Stage3;
    private IStage3Actions m_Stage3ActionsCallbackInterface;
    private readonly InputAction m_Stage3_Move;
    private readonly InputAction m_Stage3_Throw;
    private readonly InputAction m_Stage3_TurnLeft;
    private readonly InputAction m_Stage3_TurnRight;
    public struct Stage3Actions
    {
        private @PlayerControls m_Wrapper;
        public Stage3Actions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Stage3_Move;
        public InputAction @Throw => m_Wrapper.m_Stage3_Throw;
        public InputAction @TurnLeft => m_Wrapper.m_Stage3_TurnLeft;
        public InputAction @TurnRight => m_Wrapper.m_Stage3_TurnRight;
        public InputActionMap Get() { return m_Wrapper.m_Stage3; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Stage3Actions set) { return set.Get(); }
        public void SetCallbacks(IStage3Actions instance)
        {
            if (m_Wrapper.m_Stage3ActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnMove;
                @Throw.started -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnThrow;
                @Throw.performed -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnThrow;
                @Throw.canceled -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnThrow;
                @TurnLeft.started -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnTurnLeft;
                @TurnLeft.performed -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnTurnLeft;
                @TurnLeft.canceled -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnTurnLeft;
                @TurnRight.started -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnTurnRight;
                @TurnRight.performed -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnTurnRight;
                @TurnRight.canceled -= m_Wrapper.m_Stage3ActionsCallbackInterface.OnTurnRight;
            }
            m_Wrapper.m_Stage3ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Throw.started += instance.OnThrow;
                @Throw.performed += instance.OnThrow;
                @Throw.canceled += instance.OnThrow;
                @TurnLeft.started += instance.OnTurnLeft;
                @TurnLeft.performed += instance.OnTurnLeft;
                @TurnLeft.canceled += instance.OnTurnLeft;
                @TurnRight.started += instance.OnTurnRight;
                @TurnRight.performed += instance.OnTurnRight;
                @TurnRight.canceled += instance.OnTurnRight;
            }
        }
    }
    public Stage3Actions @Stage3 => new Stage3Actions(this);

    // UIInput
    private readonly InputActionMap m_UIInput;
    private IUIInputActions m_UIInputActionsCallbackInterface;
    private readonly InputAction m_UIInput_Submit;
    private readonly InputAction m_UIInput_Cancel;
    private readonly InputAction m_UIInput_Click;
    private readonly InputAction m_UIInput_Move;
    private readonly InputAction m_UIInput_A;
    private readonly InputAction m_UIInput_B;
    private readonly InputAction m_UIInput_X;
    private readonly InputAction m_UIInput_Y;
    private readonly InputAction m_UIInput_LeftCrossKey;
    private readonly InputAction m_UIInput_RightCrossKey;
    public struct UIInputActions
    {
        private @PlayerControls m_Wrapper;
        public UIInputActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Submit => m_Wrapper.m_UIInput_Submit;
        public InputAction @Cancel => m_Wrapper.m_UIInput_Cancel;
        public InputAction @Click => m_Wrapper.m_UIInput_Click;
        public InputAction @Move => m_Wrapper.m_UIInput_Move;
        public InputAction @A => m_Wrapper.m_UIInput_A;
        public InputAction @B => m_Wrapper.m_UIInput_B;
        public InputAction @X => m_Wrapper.m_UIInput_X;
        public InputAction @Y => m_Wrapper.m_UIInput_Y;
        public InputAction @LeftCrossKey => m_Wrapper.m_UIInput_LeftCrossKey;
        public InputAction @RightCrossKey => m_Wrapper.m_UIInput_RightCrossKey;
        public InputActionMap Get() { return m_Wrapper.m_UIInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIInputActions set) { return set.Get(); }
        public void SetCallbacks(IUIInputActions instance)
        {
            if (m_Wrapper.m_UIInputActionsCallbackInterface != null)
            {
                @Submit.started -= m_Wrapper.m_UIInputActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_UIInputActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_UIInputActionsCallbackInterface.OnSubmit;
                @Cancel.started -= m_Wrapper.m_UIInputActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_UIInputActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_UIInputActionsCallbackInterface.OnCancel;
                @Click.started -= m_Wrapper.m_UIInputActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_UIInputActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_UIInputActionsCallbackInterface.OnClick;
                @Move.started -= m_Wrapper.m_UIInputActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_UIInputActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_UIInputActionsCallbackInterface.OnMove;
                @A.started -= m_Wrapper.m_UIInputActionsCallbackInterface.OnA;
                @A.performed -= m_Wrapper.m_UIInputActionsCallbackInterface.OnA;
                @A.canceled -= m_Wrapper.m_UIInputActionsCallbackInterface.OnA;
                @B.started -= m_Wrapper.m_UIInputActionsCallbackInterface.OnB;
                @B.performed -= m_Wrapper.m_UIInputActionsCallbackInterface.OnB;
                @B.canceled -= m_Wrapper.m_UIInputActionsCallbackInterface.OnB;
                @X.started -= m_Wrapper.m_UIInputActionsCallbackInterface.OnX;
                @X.performed -= m_Wrapper.m_UIInputActionsCallbackInterface.OnX;
                @X.canceled -= m_Wrapper.m_UIInputActionsCallbackInterface.OnX;
                @Y.started -= m_Wrapper.m_UIInputActionsCallbackInterface.OnY;
                @Y.performed -= m_Wrapper.m_UIInputActionsCallbackInterface.OnY;
                @Y.canceled -= m_Wrapper.m_UIInputActionsCallbackInterface.OnY;
                @LeftCrossKey.started -= m_Wrapper.m_UIInputActionsCallbackInterface.OnLeftCrossKey;
                @LeftCrossKey.performed -= m_Wrapper.m_UIInputActionsCallbackInterface.OnLeftCrossKey;
                @LeftCrossKey.canceled -= m_Wrapper.m_UIInputActionsCallbackInterface.OnLeftCrossKey;
                @RightCrossKey.started -= m_Wrapper.m_UIInputActionsCallbackInterface.OnRightCrossKey;
                @RightCrossKey.performed -= m_Wrapper.m_UIInputActionsCallbackInterface.OnRightCrossKey;
                @RightCrossKey.canceled -= m_Wrapper.m_UIInputActionsCallbackInterface.OnRightCrossKey;
            }
            m_Wrapper.m_UIInputActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @A.started += instance.OnA;
                @A.performed += instance.OnA;
                @A.canceled += instance.OnA;
                @B.started += instance.OnB;
                @B.performed += instance.OnB;
                @B.canceled += instance.OnB;
                @X.started += instance.OnX;
                @X.performed += instance.OnX;
                @X.canceled += instance.OnX;
                @Y.started += instance.OnY;
                @Y.performed += instance.OnY;
                @Y.canceled += instance.OnY;
                @LeftCrossKey.started += instance.OnLeftCrossKey;
                @LeftCrossKey.performed += instance.OnLeftCrossKey;
                @LeftCrossKey.canceled += instance.OnLeftCrossKey;
                @RightCrossKey.started += instance.OnRightCrossKey;
                @RightCrossKey.performed += instance.OnRightCrossKey;
                @RightCrossKey.canceled += instance.OnRightCrossKey;
            }
        }
    }
    public UIInputActions @UIInput => new UIInputActions(this);

    // Stage_Boss
    private readonly InputActionMap m_Stage_Boss;
    private IStage_BossActions m_Stage_BossActionsCallbackInterface;
    private readonly InputAction m_Stage_Boss_Move;
    private readonly InputAction m_Stage_Boss_Camera;
    public struct Stage_BossActions
    {
        private @PlayerControls m_Wrapper;
        public Stage_BossActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Stage_Boss_Move;
        public InputAction @Camera => m_Wrapper.m_Stage_Boss_Camera;
        public InputActionMap Get() { return m_Wrapper.m_Stage_Boss; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Stage_BossActions set) { return set.Get(); }
        public void SetCallbacks(IStage_BossActions instance)
        {
            if (m_Wrapper.m_Stage_BossActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_Stage_BossActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_Stage_BossActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_Stage_BossActionsCallbackInterface.OnMove;
                @Camera.started -= m_Wrapper.m_Stage_BossActionsCallbackInterface.OnCamera;
                @Camera.performed -= m_Wrapper.m_Stage_BossActionsCallbackInterface.OnCamera;
                @Camera.canceled -= m_Wrapper.m_Stage_BossActionsCallbackInterface.OnCamera;
            }
            m_Wrapper.m_Stage_BossActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Camera.started += instance.OnCamera;
                @Camera.performed += instance.OnCamera;
                @Camera.canceled += instance.OnCamera;
            }
        }
    }
    public Stage_BossActions @Stage_Boss => new Stage_BossActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
    }
    public interface IStage1Actions
    {
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IStage2Actions
    {
        void OnSelectUp(InputAction.CallbackContext context);
        void OnSelectDown(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
        void OnPointerMove(InputAction.CallbackContext context);
    }
    public interface IStage3Actions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
        void OnTurnLeft(InputAction.CallbackContext context);
        void OnTurnRight(InputAction.CallbackContext context);
    }
    public interface IUIInputActions
    {
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnA(InputAction.CallbackContext context);
        void OnB(InputAction.CallbackContext context);
        void OnX(InputAction.CallbackContext context);
        void OnY(InputAction.CallbackContext context);
        void OnLeftCrossKey(InputAction.CallbackContext context);
        void OnRightCrossKey(InputAction.CallbackContext context);
    }
    public interface IStage_BossActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
    }
}
